### PR TITLE
Fix: Perform checksum on non-prefixed string.

### LINKED ISSUE #5: `checksum()` panics
## Describe the bug

When passing a string without a prefix, the `checksum()` function fails. 

The function accepts both prefixed and non-prefixed strings. However, indexing for characters is performed without taking this into account. This results in a panic during execution.

### PR DESCRIPTION
**Pull request by perama-v**
Addresses #5  so that the `checksum()` function correctly handles prefixed and non-prefixed strings.

I've also added some test cases from EIP-55.

### CODE REVIEW

File: tests/main.rs [hunk 1]
```diff
@@ -2,5 +2,5 @@
  fn test_validate_address() {
      // Base
      assert_eq!(eip55::validate_address("0x5aAeb6053F3E94C9b9A09f33669435E7Ef1BeAed"), true);
-     assert_eq!(eip55::checksum("0x5aAeb6053F3E94C9b9A09f33669435E7Ef1BeAed"), "0x5aAeb6053F3E94C9b9A09f33669435E7Ef1BeAed")
+     assert_eq!(eip55::checksum("0x5aaeb6053f3e94c9b9a09f33669435e7ef1beaed"), "0x5aAeb6053F3E94C9b9A09f33669435E7Ef1BeAed")
```
Comment (PumpkinSeed) [inline tests/main.rs:5]: Why did you change this one?

**Review by PumpkinSeed — COMMENTED** [review]
Thanks for the contribution. I only had one question there. :)

File: tests/main.rs (hunk 1 above)
Comment (perama-v) [reply tests/main.rs:5]: The purpose of the function is to take a non-checksummed input and return the checksum. So while `checksum()`
internally performs `.to_lower()`, it wasn't immediately apparent the test did anything if passed a checksummed address.

**Review by PumpkinSeed — APPROVED** [review]
